//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace mainService.memberReg {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="onlineregistration_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration")]
    public partial class onlineregistration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AttachDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnAccountLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnActivateAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnChangeOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnChangeRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnCreateAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnCreateUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnGenerateOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnLogin2OperationCompleted;
        
        private System.Threading.SendOrPostCallback FnLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnMemberStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnProfileDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnResetPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnSendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnSharesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnUpdatePassword2OperationCompleted;
        
        private System.Threading.SendOrPostCallback FnUpdatePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnVerifyOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback MembRegOperationCompleted;
        
        private System.Threading.SendOrPostCallback NextOfKinOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUsernameOnFirstLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnActivateAccount2OperationCompleted;
        
        private System.Threading.SendOrPostCallback fnGetBULNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback fnGetMemberNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public onlineregistration() {
            this.Url = global::mainService.Properties.Settings.Default.mainService_memberReg_onlineregistration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AttachDocumentsCompletedEventHandler AttachDocumentsCompleted;
        
        /// <remarks/>
        public event FnAccountLoginCompletedEventHandler FnAccountLoginCompleted;
        
        /// <remarks/>
        public event FnActivateAccountCompletedEventHandler FnActivateAccountCompleted;
        
        /// <remarks/>
        public event FnChangeOTPCompletedEventHandler FnChangeOTPCompleted;
        
        /// <remarks/>
        public event FnChangeRequestCompletedEventHandler FnChangeRequestCompleted;
        
        /// <remarks/>
        public event FnCreateAccountCompletedEventHandler FnCreateAccountCompleted;
        
        /// <remarks/>
        public event FnCreateUsernameCompletedEventHandler FnCreateUsernameCompleted;
        
        /// <remarks/>
        public event FnGenerateOTPCompletedEventHandler FnGenerateOTPCompleted;
        
        /// <remarks/>
        public event FnLogin2CompletedEventHandler FnLogin2Completed;
        
        /// <remarks/>
        public event FnLoginCompletedEventHandler FnLoginCompleted;
        
        /// <remarks/>
        public event FnMemberStatementCompletedEventHandler FnMemberStatementCompleted;
        
        /// <remarks/>
        public event FnProfileDetailsCompletedEventHandler FnProfileDetailsCompleted;
        
        /// <remarks/>
        public event FnResetPasswordCompletedEventHandler FnResetPasswordCompleted;
        
        /// <remarks/>
        public event FnSendOTPCompletedEventHandler FnSendOTPCompleted;
        
        /// <remarks/>
        public event FnSharesCompletedEventHandler FnSharesCompleted;
        
        /// <remarks/>
        public event FnUpdatePassword2CompletedEventHandler FnUpdatePassword2Completed;
        
        /// <remarks/>
        public event FnUpdatePasswordCompletedEventHandler FnUpdatePasswordCompleted;
        
        /// <remarks/>
        public event FnVerifyOTPCompletedEventHandler FnVerifyOTPCompleted;
        
        /// <remarks/>
        public event MembRegCompletedEventHandler MembRegCompleted;
        
        /// <remarks/>
        public event NextOfKinCompletedEventHandler NextOfKinCompleted;
        
        /// <remarks/>
        public event SetUsernameOnFirstLoginCompletedEventHandler SetUsernameOnFirstLoginCompleted;
        
        /// <remarks/>
        public event fnActivateAccount2CompletedEventHandler fnActivateAccount2Completed;
        
        /// <remarks/>
        public event fnGetBULNumberCompletedEventHandler fnGetBULNumberCompleted;
        
        /// <remarks/>
        public event fnGetMemberNoCompletedEventHandler fnGetMemberNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:AttachDocuments", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="AttachDocuments_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool AttachDocuments(string docNo, string fileName, string attachment) {
            object[] results = this.Invoke("AttachDocuments", new object[] {
                        docNo,
                        fileName,
                        attachment});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AttachDocumentsAsync(string docNo, string fileName, string attachment) {
            this.AttachDocumentsAsync(docNo, fileName, attachment, null);
        }
        
        /// <remarks/>
        public void AttachDocumentsAsync(string docNo, string fileName, string attachment, object userState) {
            if ((this.AttachDocumentsOperationCompleted == null)) {
                this.AttachDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAttachDocumentsOperationCompleted);
            }
            this.InvokeAsync("AttachDocuments", new object[] {
                        docNo,
                        fileName,
                        attachment}, this.AttachDocumentsOperationCompleted, userState);
        }
        
        private void OnAttachDocumentsOperationCompleted(object arg) {
            if ((this.AttachDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AttachDocumentsCompleted(this, new AttachDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnAccountLogin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnAccountLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnAccountLogin(string username, string password) {
            object[] results = this.Invoke("FnAccountLogin", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnAccountLoginAsync(string username, string password) {
            this.FnAccountLoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void FnAccountLoginAsync(string username, string password, object userState) {
            if ((this.FnAccountLoginOperationCompleted == null)) {
                this.FnAccountLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnAccountLoginOperationCompleted);
            }
            this.InvokeAsync("FnAccountLogin", new object[] {
                        username,
                        password}, this.FnAccountLoginOperationCompleted, userState);
        }
        
        private void OnFnAccountLoginOperationCompleted(object arg) {
            if ((this.FnAccountLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnAccountLoginCompleted(this, new FnAccountLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnActivateAccount", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnActivateAccount_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnActivateAccount(string fullName, string mobileNumber, string email) {
            object[] results = this.Invoke("FnActivateAccount", new object[] {
                        fullName,
                        mobileNumber,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnActivateAccountAsync(string fullName, string mobileNumber, string email) {
            this.FnActivateAccountAsync(fullName, mobileNumber, email, null);
        }
        
        /// <remarks/>
        public void FnActivateAccountAsync(string fullName, string mobileNumber, string email, object userState) {
            if ((this.FnActivateAccountOperationCompleted == null)) {
                this.FnActivateAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnActivateAccountOperationCompleted);
            }
            this.InvokeAsync("FnActivateAccount", new object[] {
                        fullName,
                        mobileNumber,
                        email}, this.FnActivateAccountOperationCompleted, userState);
        }
        
        private void OnFnActivateAccountOperationCompleted(object arg) {
            if ((this.FnActivateAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnActivateAccountCompleted(this, new FnActivateAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnChangeOTP", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnChangeOTP_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnChangeOTP(string emailAddress) {
            object[] results = this.Invoke("FnChangeOTP", new object[] {
                        emailAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnChangeOTPAsync(string emailAddress) {
            this.FnChangeOTPAsync(emailAddress, null);
        }
        
        /// <remarks/>
        public void FnChangeOTPAsync(string emailAddress, object userState) {
            if ((this.FnChangeOTPOperationCompleted == null)) {
                this.FnChangeOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnChangeOTPOperationCompleted);
            }
            this.InvokeAsync("FnChangeOTP", new object[] {
                        emailAddress}, this.FnChangeOTPOperationCompleted, userState);
        }
        
        private void OnFnChangeOTPOperationCompleted(object arg) {
            if ((this.FnChangeOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnChangeOTPCompleted(this, new FnChangeOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnChangeRequest", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnChangeRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnChangeRequest(string email, string request) {
            object[] results = this.Invoke("FnChangeRequest", new object[] {
                        email,
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnChangeRequestAsync(string email, string request) {
            this.FnChangeRequestAsync(email, request, null);
        }
        
        /// <remarks/>
        public void FnChangeRequestAsync(string email, string request, object userState) {
            if ((this.FnChangeRequestOperationCompleted == null)) {
                this.FnChangeRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnChangeRequestOperationCompleted);
            }
            this.InvokeAsync("FnChangeRequest", new object[] {
                        email,
                        request}, this.FnChangeRequestOperationCompleted, userState);
        }
        
        private void OnFnChangeRequestOperationCompleted(object arg) {
            if ((this.FnChangeRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnChangeRequestCompleted(this, new FnChangeRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnCreateAccount", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnCreateAccount_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnCreateAccount(string emailAddress, string username, string hashedPassword) {
            object[] results = this.Invoke("FnCreateAccount", new object[] {
                        emailAddress,
                        username,
                        hashedPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnCreateAccountAsync(string emailAddress, string username, string hashedPassword) {
            this.FnCreateAccountAsync(emailAddress, username, hashedPassword, null);
        }
        
        /// <remarks/>
        public void FnCreateAccountAsync(string emailAddress, string username, string hashedPassword, object userState) {
            if ((this.FnCreateAccountOperationCompleted == null)) {
                this.FnCreateAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnCreateAccountOperationCompleted);
            }
            this.InvokeAsync("FnCreateAccount", new object[] {
                        emailAddress,
                        username,
                        hashedPassword}, this.FnCreateAccountOperationCompleted, userState);
        }
        
        private void OnFnCreateAccountOperationCompleted(object arg) {
            if ((this.FnCreateAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnCreateAccountCompleted(this, new FnCreateAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnCreateUsername", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnCreateUsername_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnCreateUsername(string emailAddress, string username) {
            object[] results = this.Invoke("FnCreateUsername", new object[] {
                        emailAddress,
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnCreateUsernameAsync(string emailAddress, string username) {
            this.FnCreateUsernameAsync(emailAddress, username, null);
        }
        
        /// <remarks/>
        public void FnCreateUsernameAsync(string emailAddress, string username, object userState) {
            if ((this.FnCreateUsernameOperationCompleted == null)) {
                this.FnCreateUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnCreateUsernameOperationCompleted);
            }
            this.InvokeAsync("FnCreateUsername", new object[] {
                        emailAddress,
                        username}, this.FnCreateUsernameOperationCompleted, userState);
        }
        
        private void OnFnCreateUsernameOperationCompleted(object arg) {
            if ((this.FnCreateUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnCreateUsernameCompleted(this, new FnCreateUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnGenerateOTP", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnGenerateOTP_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public int FnGenerateOTP() {
            object[] results = this.Invoke("FnGenerateOTP", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FnGenerateOTPAsync() {
            this.FnGenerateOTPAsync(null);
        }
        
        /// <remarks/>
        public void FnGenerateOTPAsync(object userState) {
            if ((this.FnGenerateOTPOperationCompleted == null)) {
                this.FnGenerateOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnGenerateOTPOperationCompleted);
            }
            this.InvokeAsync("FnGenerateOTP", new object[0], this.FnGenerateOTPOperationCompleted, userState);
        }
        
        private void OnFnGenerateOTPOperationCompleted(object arg) {
            if ((this.FnGenerateOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnGenerateOTPCompleted(this, new FnGenerateOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnLogin2", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnLogin2_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool FnLogin2(string emailOrUsername, string password) {
            object[] results = this.Invoke("FnLogin2", new object[] {
                        emailOrUsername,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FnLogin2Async(string emailOrUsername, string password) {
            this.FnLogin2Async(emailOrUsername, password, null);
        }
        
        /// <remarks/>
        public void FnLogin2Async(string emailOrUsername, string password, object userState) {
            if ((this.FnLogin2OperationCompleted == null)) {
                this.FnLogin2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnLogin2OperationCompleted);
            }
            this.InvokeAsync("FnLogin2", new object[] {
                        emailOrUsername,
                        password}, this.FnLogin2OperationCompleted, userState);
        }
        
        private void OnFnLogin2OperationCompleted(object arg) {
            if ((this.FnLogin2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnLogin2Completed(this, new FnLogin2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnLogin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool FnLogin(string emailAddress, string password) {
            object[] results = this.Invoke("FnLogin", new object[] {
                        emailAddress,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FnLoginAsync(string emailAddress, string password) {
            this.FnLoginAsync(emailAddress, password, null);
        }
        
        /// <remarks/>
        public void FnLoginAsync(string emailAddress, string password, object userState) {
            if ((this.FnLoginOperationCompleted == null)) {
                this.FnLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnLoginOperationCompleted);
            }
            this.InvokeAsync("FnLogin", new object[] {
                        emailAddress,
                        password}, this.FnLoginOperationCompleted, userState);
        }
        
        private void OnFnLoginOperationCompleted(object arg) {
            if ((this.FnLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnLoginCompleted(this, new FnLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnMemberStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnMemberStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnMemberStatement(string email, string bulShoNo) {
            object[] results = this.Invoke("FnMemberStatement", new object[] {
                        email,
                        bulShoNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnMemberStatementAsync(string email, string bulShoNo) {
            this.FnMemberStatementAsync(email, bulShoNo, null);
        }
        
        /// <remarks/>
        public void FnMemberStatementAsync(string email, string bulShoNo, object userState) {
            if ((this.FnMemberStatementOperationCompleted == null)) {
                this.FnMemberStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnMemberStatementOperationCompleted);
            }
            this.InvokeAsync("FnMemberStatement", new object[] {
                        email,
                        bulShoNo}, this.FnMemberStatementOperationCompleted, userState);
        }
        
        private void OnFnMemberStatementOperationCompleted(object arg) {
            if ((this.FnMemberStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnMemberStatementCompleted(this, new FnMemberStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnProfileDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnProfileDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnProfileDetails(string bEmail, string bulNo) {
            object[] results = this.Invoke("FnProfileDetails", new object[] {
                        bEmail,
                        bulNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnProfileDetailsAsync(string bEmail, string bulNo) {
            this.FnProfileDetailsAsync(bEmail, bulNo, null);
        }
        
        /// <remarks/>
        public void FnProfileDetailsAsync(string bEmail, string bulNo, object userState) {
            if ((this.FnProfileDetailsOperationCompleted == null)) {
                this.FnProfileDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnProfileDetailsOperationCompleted);
            }
            this.InvokeAsync("FnProfileDetails", new object[] {
                        bEmail,
                        bulNo}, this.FnProfileDetailsOperationCompleted, userState);
        }
        
        private void OnFnProfileDetailsOperationCompleted(object arg) {
            if ((this.FnProfileDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnProfileDetailsCompleted(this, new FnProfileDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnResetPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnResetPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnResetPassword(string accountNumber, string password, string confirmPassword, int otpCode) {
            object[] results = this.Invoke("FnResetPassword", new object[] {
                        accountNumber,
                        password,
                        confirmPassword,
                        otpCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnResetPasswordAsync(string accountNumber, string password, string confirmPassword, int otpCode) {
            this.FnResetPasswordAsync(accountNumber, password, confirmPassword, otpCode, null);
        }
        
        /// <remarks/>
        public void FnResetPasswordAsync(string accountNumber, string password, string confirmPassword, int otpCode, object userState) {
            if ((this.FnResetPasswordOperationCompleted == null)) {
                this.FnResetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnResetPasswordOperationCompleted);
            }
            this.InvokeAsync("FnResetPassword", new object[] {
                        accountNumber,
                        password,
                        confirmPassword,
                        otpCode}, this.FnResetPasswordOperationCompleted, userState);
        }
        
        private void OnFnResetPasswordOperationCompleted(object arg) {
            if ((this.FnResetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnResetPasswordCompleted(this, new FnResetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnSendOTP", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnSendOTP_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnSendOTP(string emailAddress) {
            object[] results = this.Invoke("FnSendOTP", new object[] {
                        emailAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnSendOTPAsync(string emailAddress) {
            this.FnSendOTPAsync(emailAddress, null);
        }
        
        /// <remarks/>
        public void FnSendOTPAsync(string emailAddress, object userState) {
            if ((this.FnSendOTPOperationCompleted == null)) {
                this.FnSendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnSendOTPOperationCompleted);
            }
            this.InvokeAsync("FnSendOTP", new object[] {
                        emailAddress}, this.FnSendOTPOperationCompleted, userState);
        }
        
        private void OnFnSendOTPOperationCompleted(object arg) {
            if ((this.FnSendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnSendOTPCompleted(this, new FnSendOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnShares", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnShares_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnShares(string email, string bulShoNo) {
            object[] results = this.Invoke("FnShares", new object[] {
                        email,
                        bulShoNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnSharesAsync(string email, string bulShoNo) {
            this.FnSharesAsync(email, bulShoNo, null);
        }
        
        /// <remarks/>
        public void FnSharesAsync(string email, string bulShoNo, object userState) {
            if ((this.FnSharesOperationCompleted == null)) {
                this.FnSharesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnSharesOperationCompleted);
            }
            this.InvokeAsync("FnShares", new object[] {
                        email,
                        bulShoNo}, this.FnSharesOperationCompleted, userState);
        }
        
        private void OnFnSharesOperationCompleted(object arg) {
            if ((this.FnSharesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnSharesCompleted(this, new FnSharesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnUpdatePassword2", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnUpdatePassword2_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnUpdatePassword2(string emailAddress, string hashedPassword) {
            object[] results = this.Invoke("FnUpdatePassword2", new object[] {
                        emailAddress,
                        hashedPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnUpdatePassword2Async(string emailAddress, string hashedPassword) {
            this.FnUpdatePassword2Async(emailAddress, hashedPassword, null);
        }
        
        /// <remarks/>
        public void FnUpdatePassword2Async(string emailAddress, string hashedPassword, object userState) {
            if ((this.FnUpdatePassword2OperationCompleted == null)) {
                this.FnUpdatePassword2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnUpdatePassword2OperationCompleted);
            }
            this.InvokeAsync("FnUpdatePassword2", new object[] {
                        emailAddress,
                        hashedPassword}, this.FnUpdatePassword2OperationCompleted, userState);
        }
        
        private void OnFnUpdatePassword2OperationCompleted(object arg) {
            if ((this.FnUpdatePassword2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnUpdatePassword2Completed(this, new FnUpdatePassword2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnUpdatePassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnUpdatePassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnUpdatePassword(string emailAddress, string hashedPassword) {
            object[] results = this.Invoke("FnUpdatePassword", new object[] {
                        emailAddress,
                        hashedPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnUpdatePasswordAsync(string emailAddress, string hashedPassword) {
            this.FnUpdatePasswordAsync(emailAddress, hashedPassword, null);
        }
        
        /// <remarks/>
        public void FnUpdatePasswordAsync(string emailAddress, string hashedPassword, object userState) {
            if ((this.FnUpdatePasswordOperationCompleted == null)) {
                this.FnUpdatePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnUpdatePasswordOperationCompleted);
            }
            this.InvokeAsync("FnUpdatePassword", new object[] {
                        emailAddress,
                        hashedPassword}, this.FnUpdatePasswordOperationCompleted, userState);
        }
        
        private void OnFnUpdatePasswordOperationCompleted(object arg) {
            if ((this.FnUpdatePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnUpdatePasswordCompleted(this, new FnUpdatePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:FnVerifyOTP", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="FnVerifyOTP_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnVerifyOTP(int otp, string emailAddress) {
            object[] results = this.Invoke("FnVerifyOTP", new object[] {
                        otp,
                        emailAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnVerifyOTPAsync(int otp, string emailAddress) {
            this.FnVerifyOTPAsync(otp, emailAddress, null);
        }
        
        /// <remarks/>
        public void FnVerifyOTPAsync(int otp, string emailAddress, object userState) {
            if ((this.FnVerifyOTPOperationCompleted == null)) {
                this.FnVerifyOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnVerifyOTPOperationCompleted);
            }
            this.InvokeAsync("FnVerifyOTP", new object[] {
                        otp,
                        emailAddress}, this.FnVerifyOTPOperationCompleted, userState);
        }
        
        private void OnFnVerifyOTPOperationCompleted(object arg) {
            if ((this.FnVerifyOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnVerifyOTPCompleted(this, new FnVerifyOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:MembReg", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="MembReg_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string MembReg(string firstName, string midName, string lastName, string name, string roCode, string mobileNo, string country, string town, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateOfBirth, string email, int gender, int maritalStatus, int employementInfo, int accountC, int membershipType) {
            object[] results = this.Invoke("MembReg", new object[] {
                        firstName,
                        midName,
                        lastName,
                        name,
                        roCode,
                        mobileNo,
                        country,
                        town,
                        dateOfBirth,
                        email,
                        gender,
                        maritalStatus,
                        employementInfo,
                        accountC,
                        membershipType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MembRegAsync(string firstName, string midName, string lastName, string name, string roCode, string mobileNo, string country, string town, System.DateTime dateOfBirth, string email, int gender, int maritalStatus, int employementInfo, int accountC, int membershipType) {
            this.MembRegAsync(firstName, midName, lastName, name, roCode, mobileNo, country, town, dateOfBirth, email, gender, maritalStatus, employementInfo, accountC, membershipType, null);
        }
        
        /// <remarks/>
        public void MembRegAsync(
                    string firstName, 
                    string midName, 
                    string lastName, 
                    string name, 
                    string roCode, 
                    string mobileNo, 
                    string country, 
                    string town, 
                    System.DateTime dateOfBirth, 
                    string email, 
                    int gender, 
                    int maritalStatus, 
                    int employementInfo, 
                    int accountC, 
                    int membershipType, 
                    object userState) {
            if ((this.MembRegOperationCompleted == null)) {
                this.MembRegOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMembRegOperationCompleted);
            }
            this.InvokeAsync("MembReg", new object[] {
                        firstName,
                        midName,
                        lastName,
                        name,
                        roCode,
                        mobileNo,
                        country,
                        town,
                        dateOfBirth,
                        email,
                        gender,
                        maritalStatus,
                        employementInfo,
                        accountC,
                        membershipType}, this.MembRegOperationCompleted, userState);
        }
        
        private void OnMembRegOperationCompleted(object arg) {
            if ((this.MembRegCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MembRegCompleted(this, new MembRegCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:NextOfKin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="NextOfKin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool NextOfKin(string name, string telNo, string appNo) {
            object[] results = this.Invoke("NextOfKin", new object[] {
                        name,
                        telNo,
                        appNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NextOfKinAsync(string name, string telNo, string appNo) {
            this.NextOfKinAsync(name, telNo, appNo, null);
        }
        
        /// <remarks/>
        public void NextOfKinAsync(string name, string telNo, string appNo, object userState) {
            if ((this.NextOfKinOperationCompleted == null)) {
                this.NextOfKinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNextOfKinOperationCompleted);
            }
            this.InvokeAsync("NextOfKin", new object[] {
                        name,
                        telNo,
                        appNo}, this.NextOfKinOperationCompleted, userState);
        }
        
        private void OnNextOfKinOperationCompleted(object arg) {
            if ((this.NextOfKinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NextOfKinCompleted(this, new NextOfKinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:SetUsernameOnFirstLogi" +
            "n", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="SetUsernameOnFirstLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetUsernameOnFirstLogin(string emailOrUsername) {
            this.Invoke("SetUsernameOnFirstLogin", new object[] {
                        emailOrUsername});
        }
        
        /// <remarks/>
        public void SetUsernameOnFirstLoginAsync(string emailOrUsername) {
            this.SetUsernameOnFirstLoginAsync(emailOrUsername, null);
        }
        
        /// <remarks/>
        public void SetUsernameOnFirstLoginAsync(string emailOrUsername, object userState) {
            if ((this.SetUsernameOnFirstLoginOperationCompleted == null)) {
                this.SetUsernameOnFirstLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUsernameOnFirstLoginOperationCompleted);
            }
            this.InvokeAsync("SetUsernameOnFirstLogin", new object[] {
                        emailOrUsername}, this.SetUsernameOnFirstLoginOperationCompleted, userState);
        }
        
        private void OnSetUsernameOnFirstLoginOperationCompleted(object arg) {
            if ((this.SetUsernameOnFirstLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUsernameOnFirstLoginCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:fnActivateAccount2", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="fnActivateAccount2_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string fnActivateAccount2(string memberNumber, string email) {
            object[] results = this.Invoke("fnActivateAccount2", new object[] {
                        memberNumber,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnActivateAccount2Async(string memberNumber, string email) {
            this.fnActivateAccount2Async(memberNumber, email, null);
        }
        
        /// <remarks/>
        public void fnActivateAccount2Async(string memberNumber, string email, object userState) {
            if ((this.fnActivateAccount2OperationCompleted == null)) {
                this.fnActivateAccount2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnActivateAccount2OperationCompleted);
            }
            this.InvokeAsync("fnActivateAccount2", new object[] {
                        memberNumber,
                        email}, this.fnActivateAccount2OperationCompleted, userState);
        }
        
        private void OnfnActivateAccount2OperationCompleted(object arg) {
            if ((this.fnActivateAccount2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnActivateAccount2Completed(this, new fnActivateAccount2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:fnGetBULNumber", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="fnGetBULNumber_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string fnGetBULNumber(string username) {
            object[] results = this.Invoke("fnGetBULNumber", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnGetBULNumberAsync(string username) {
            this.fnGetBULNumberAsync(username, null);
        }
        
        /// <remarks/>
        public void fnGetBULNumberAsync(string username, object userState) {
            if ((this.fnGetBULNumberOperationCompleted == null)) {
                this.fnGetBULNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnGetBULNumberOperationCompleted);
            }
            this.InvokeAsync("fnGetBULNumber", new object[] {
                        username}, this.fnGetBULNumberOperationCompleted, userState);
        }
        
        private void OnfnGetBULNumberOperationCompleted(object arg) {
            if ((this.fnGetBULNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnGetBULNumberCompleted(this, new fnGetBULNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/onlineregistration:fnGetMemberNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", ResponseElementName="fnGetMemberNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/onlineregistration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string fnGetMemberNo(string email) {
            object[] results = this.Invoke("fnGetMemberNo", new object[] {
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fnGetMemberNoAsync(string email) {
            this.fnGetMemberNoAsync(email, null);
        }
        
        /// <remarks/>
        public void fnGetMemberNoAsync(string email, object userState) {
            if ((this.fnGetMemberNoOperationCompleted == null)) {
                this.fnGetMemberNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfnGetMemberNoOperationCompleted);
            }
            this.InvokeAsync("fnGetMemberNo", new object[] {
                        email}, this.fnGetMemberNoOperationCompleted, userState);
        }
        
        private void OnfnGetMemberNoOperationCompleted(object arg) {
            if ((this.fnGetMemberNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fnGetMemberNoCompleted(this, new fnGetMemberNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AttachDocumentsCompletedEventHandler(object sender, AttachDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AttachDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AttachDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnAccountLoginCompletedEventHandler(object sender, FnAccountLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnAccountLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnAccountLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnActivateAccountCompletedEventHandler(object sender, FnActivateAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnActivateAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnActivateAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnChangeOTPCompletedEventHandler(object sender, FnChangeOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnChangeOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnChangeOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnChangeRequestCompletedEventHandler(object sender, FnChangeRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnChangeRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnChangeRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnCreateAccountCompletedEventHandler(object sender, FnCreateAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnCreateAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnCreateAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnCreateUsernameCompletedEventHandler(object sender, FnCreateUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnCreateUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnCreateUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnGenerateOTPCompletedEventHandler(object sender, FnGenerateOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnGenerateOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnGenerateOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnLogin2CompletedEventHandler(object sender, FnLogin2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnLogin2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnLogin2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnLoginCompletedEventHandler(object sender, FnLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnMemberStatementCompletedEventHandler(object sender, FnMemberStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnMemberStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnMemberStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnProfileDetailsCompletedEventHandler(object sender, FnProfileDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnProfileDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnProfileDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnResetPasswordCompletedEventHandler(object sender, FnResetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnSendOTPCompletedEventHandler(object sender, FnSendOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnSendOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnSendOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnSharesCompletedEventHandler(object sender, FnSharesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnSharesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnSharesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnUpdatePassword2CompletedEventHandler(object sender, FnUpdatePassword2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnUpdatePassword2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnUpdatePassword2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnUpdatePasswordCompletedEventHandler(object sender, FnUpdatePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnUpdatePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnUpdatePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FnVerifyOTPCompletedEventHandler(object sender, FnVerifyOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnVerifyOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnVerifyOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void MembRegCompletedEventHandler(object sender, MembRegCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MembRegCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MembRegCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void NextOfKinCompletedEventHandler(object sender, NextOfKinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NextOfKinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NextOfKinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SetUsernameOnFirstLoginCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void fnActivateAccount2CompletedEventHandler(object sender, fnActivateAccount2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnActivateAccount2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnActivateAccount2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void fnGetBULNumberCompletedEventHandler(object sender, fnGetBULNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnGetBULNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnGetBULNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void fnGetMemberNoCompletedEventHandler(object sender, fnGetMemberNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fnGetMemberNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fnGetMemberNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591